######################################################################
# Automatically generated by qmake (3.1) Wed Feb 4 15:41:35 2026
######################################################################

TEMPLATE = app
TARGET = 03_Tabla_Assays
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += assayapiclient.h \
           assaysapiclient.h \
           dialogoassay.h \
           dtablaassays.h \
           jsonassay.h \
           jsonassays.h \
           ventanaprincipal.h
FORMS += dialogoassay.ui dtablaassays.ui ventanaprincipal.ui
SOURCES += assayapiclient.cpp \
           assaysapiclient.cpp \
           dialogoassay.cpp \
           dtablaassays.cpp \
           jsonassay.cpp \
           jsonassays.cpp \
           main.cpp \
           ventanaprincipal.cpp
QT += widgets network
